I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/dse-event_dispatcher.rpy", line 299, in script
    return
Exception: Could not find return label (u'game/script.rpy', 1649150960, 3).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/dse-event_dispatcher.rpy", line 299, in script
    return
  File "renpy/ast.py", line 1567, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "renpy/execution.py", line 710, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label (u'game/script.rpy', 1649150960, 3).

Windows-10-10.0.22000
Ren'Py 7.4.11.2266
 
Mon Apr 18 14:11:01 2022
